base:
  build: deploy/docker/base
app:
  build: .
develop:
  build: deploy/docker/develop
  working_dir: /srv/docker-volume/repo
  volumes:
    - /var/lib/docker-volume:/srv/docker-volume/repo:rw
testing:
  build: deploy/docker/testing
  working_dir: /srv/docker-volume/repo
  volumes:
    - /var/lib/docker-volume:/srv/docker-volume/repo:rw
ham:
  image: busybox:latest
  volumes:
    - /var/lib/docker-volume/ham:/var/lib/docker-volume:rw
spam:
  image: busybox:latest
  volumes:
    - /var/lib/docker-volume/spam:/var/lib/docker-volume:rw
